apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appstore.fullname" . }}-sa
---
# These permissions must only encompass the API calls that Tycho makes.
# Ref: https://github.com/helxplatform/tycho/blob/master/tycho/kube.py
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "appstore.fullname" . }}-role
rules:
- apiGroups:
  - ""
  resources:
    - pods
    - services
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - ""
  resources:
    - secrets
    - persistentvolumeclaims
  vebs:
    # Listing secrets can be removed after https://github.com/helxplatform/development/issues/852
    - list
- apiGroups:
  - "apps"
  resources:
    - deployments
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "appstore.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "appstore.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "appstore.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.useSparkServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: spark
  namespace: {{ .Release.Namespace }}
{{- end }}
