name: Trigger-Helm-Charts
on:
  push:
    # branches:
    #   - main
    #   - master
    # # paths-ignore:
    # #   - .github/workflows/*
    # #   - .github/*
jobs:
  Get-Chart-Info:
    credentials:
      runs-on: ubuntu-latest
    outputs:
      APPREPO: ${{ steps.chartInfo.outputs.APPREPO }}
      ACTOR: ${{ steps.chartInfo.outputs.ACTOR }}
      TOKEN: ${{ steps.chartInfo.outputs.TOKEN }}
      
    steps:
      - name: chartInfo
        id: chartInfo
        run: |
          echo "APPREPO=${{ github.repository }}" >> GITHUB_OUTPUT
          echo "ACTOR=${{ github.actor }}" >> GITHUB_OUTPUT
          echo "TOKEN=${{ secrets.GH_TOKEN }}" >> GITHUB_OUTPUT
      