# This chart catches changes and then pushed to main branch
# Tests, Updates Dependency and Packages, then pushes to 
# our parent repo that holds all Helx Charts Helm-Charts

name: Trigger-Helm-Charts
on:
  push:
    branches:
      - main 
      - master
    paths-ignore:
      - .github/workflows/*
      - .github/*
jobs:
    build-push-release:
        uses: pchachicho/renci-github-actions/.github/workflows/trigger-helm-charts.yml@main
        secrets: inherit


    

